services:
    mysql:
        container_name: mysql
        image: mysql
        restart: always
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - main
        ports:
            - 3306:3306
        environment:
            MYSQL_LOG_BIN: OFF
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: noteApp

    backend:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
            target: Build
        ports:
            - 5000:5000
            - 9229:9229 # for debuging!
        volumes:
            - .:/build
            # - /build/node_modules
        depends_on:
            - mysql
        networks:
            - main
        restart: always
        command: bun serve
        environment:
            PORT: 5000
            NODE_ENV: development
            DATABASE_URL: mysql://127.0.0.1:3306/noteApp

networks:
    main:
volumes:
    mysql_data:
